In [1]:
import numpy as np

# Создание массивов

In [2]:
arr1 = np.array([1, 2, 3, 5, 7], dtype='float32')

In [3]:
for el in arr1:
    print(el)

1.0
2.0
3.0
5.0
7.0


## Вложенные списки преобразуются в многомерный массив

In [4]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Создание массивов с нуля

In [5]:
np.zeros(10, dtype=int) # массив нулей

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Создание массивов из единиц

In [6]:
ones = np.ones((3, 5), dtype=float)

In [7]:
np.full((3, 5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

### Создание массива заполненный линейной последовательностью начинающейся с 0 и заканчивающийся 20 с шагом 2

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Создание массива из пяти значений равномерно располагающихся между 0 и 1

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Создание массива 3 на 3 нормально распределенных случайных значений от 0 до 1

In [10]:
np.random.random((3, 3))

array([[0.94993637, 0.0738665 , 0.01954762],
       [0.25626641, 0.24895918, 0.16953827],
       [0.04393525, 0.9573667 , 0.01813077]])

### Создание массива 3 на 3 нормально распределенных случайных значений с медианой 0 и стандартным отклонением 1

In [11]:
np.random.normal(0, 1, (3, 3))

array([[ 0.29817107, -0.33094472, -1.084203  ],
       [-1.17347458,  2.01554265,  0.20901704],
       [ 1.00856722,  1.1494818 , -0.62331274]])

In [12]:
np.eye(3, dtype=int)  # единичная диагональная матрица

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Создаем массив размером 3 на 3 случайных целых чисел в промежутке (0, 10)

In [13]:
np.random.randint(0, 10, (3,3))

array([[4, 5, 4],
       [0, 3, 5],
       [6, 9, 7]])

## Введение в массивы библиотеки Numpy

### Атрибуты массивов библиотеки Numpy

In [14]:
x1 = np.random.randint(10, size=6) # одномерный массив
x2 = np.random.randint(10, size=(3, 4)) # двумерный массив
x3 = np.random.randint(10, size=(3, 4, 5)) # трехмерный массив

In [15]:
print('x3 ndim: ', x3.ndim) # размерность
print('x3 shape: ', x3.shape) # размер каждого измерения
print('x3 size: ', x3.size ) # общий размер массива 

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [16]:
print('dtype:', x3.dtype)

dtype: int64


In [17]:
print('itemsize:', x3.itemsize, 'bytes') # размер каждого элемента массива

itemsize: 8 bytes


In [18]:
print('nbytes:', x3.nbytes, 'bytes') # размер всего массива

nbytes: 480 bytes


### Индексация массива: доступ к отдельным элементам

In [19]:
x1

array([1, 8, 7, 3, 5, 1])

In [20]:
x1[0]

1

In [21]:
x1[4]

5

In [22]:
x1[-1]

1

In [23]:
x2

array([[3, 5, 3, 1],
       [3, 2, 4, 6],
       [6, 6, 2, 2]])

In [24]:
x2[0,0]

3

In [25]:
x2[2,0]

6

In [26]:
x2[2, 0] = 100

In [27]:
x2

array([[  3,   5,   3,   1],
       [  3,   2,   4,   6],
       [100,   6,   2,   2]])

In [28]:
x1[0]=3.1459 # Значение с плавающей точкой будет усечено

In [29]:
x1

array([3, 8, 7, 3, 5, 1])

### Срезы массивов: доступ к подмассивам

#### Одномерные массивы

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:5] # первые пять элементов

array([0, 1, 2, 3, 4])

In [32]:
x[5:] # элементы после индекса = 5

array([5, 6, 7, 8, 9])

In [33]:
x[::2] # каждый второй элемент

array([0, 2, 4, 6, 8])

In [34]:
x[1::2] # каждый второй элемент начиная с индекса 1

array([1, 3, 5, 7, 9])

####  Многомерные подмассивы

In [35]:
x2

array([[  3,   5,   3,   1],
       [  3,   2,   4,   6],
       [100,   6,   2,   2]])

In [36]:
x2[:2, :3] # выберет первые две строки и первые три столбца. Или 
       # первые два элемента списка - [[mas1], [mas2]]. Второй :3 - выберет первые 
#     три из каждой выбранной mas1, mas2

array([[3, 5, 3],
       [3, 2, 4]])

In [37]:
x2[:3, ::2]

array([[  3,   3],
       [  3,   4],
       [100,   2]])

In [38]:
x2[::-1, ::-1] # Первый слайс (::-1) [mas1, mas2, mas3] перевернет массив в [mas3, mas2, mas1].
               # Второй слайс (::-1) перевернет содержимое каждого из массивов mas1, mas2 и mas3

array([[  2,   2,   6, 100],
       [  6,   4,   2,   3],
       [  1,   3,   5,   3]])

### Доступ к строкам и столбцам массива 

In [39]:
print(x2[:, 0]) # Первый столбец массива

[  3   3 100]


In [40]:
print(x2[0, :]) # Первая строка массива

[3 5 3 1]


#### Срезы массивов возвращают представления, а не копии

### Создание копий массивов

#### метод copy()

In [41]:
x2


array([[  3,   5,   3,   1],
       [  3,   2,   4,   6],
       [100,   6,   2,   2]])

In [42]:
x2_sub_copy = x2[:2, :2].copy()

In [43]:
x2_sub_copy

array([[3, 5],
       [3, 2]])

In [44]:
x2_sub_copy[0][0] = 333

In [45]:
x2_sub_copy

array([[333,   5],
       [  3,   2]])

In [46]:
x2

array([[  3,   5,   3,   1],
       [  3,   2,   4,   6],
       [100,   6,   2,   2]])

### Изменение формы массивов

In [47]:
grid = np.arange(1, 10).reshape(3,3)

In [48]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [50]:
# Преобразование в вектор-строку с помощью reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [51]:
x

array([1, 2, 3])

In [52]:
# Преобразование в вектор-строку посредством newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [53]:
# Преобразование в вектор столбец с помощью reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [54]:
# Преобразование в вектор-столбец посредством newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

### Слияние массивов

In [55]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) # слияние методом concatenate

array([1, 2, 3, 3, 2, 1])

In [56]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z])) # Можно объединять более двух массивов

[ 1  2  3  3  2  1 99 99 99]


In [57]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [58]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([grid, grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6]])

In [60]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([x, grid]) # объединение массива по вертикали

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [61]:
y = np.array([[99], [99]])
np.hstack([grid, y]) # Горизонтальное объединение массива

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [62]:
help(np.concatenate)

Help on built-in function concatenate in module numpy.core.multiarray:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None)
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    
    Returns
    -------
    res : ndarray
        The concatenated array.
    
    See Also
    --------
    ma.concatenate : Concatenate function that preserves input masks.
    array_split : Split an array into multiple sub-arrays of equal or
                  near-equal size.
  