In [9]:
import numpy as np

# Создание массивов

In [23]:
arr1 = np.array([1, 2, 3, 5, 7], dtype='float32')

In [25]:
for el in arr1:
    print(el)

1.0
2.0
3.0
5.0
7.0


## Вложенные списки преобразуются в многомерный массив

In [40]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Создание массивов с нуля

In [47]:
np.zeros(10, dtype=int) # массив нулей

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Создание массивов из единиц

In [50]:
ones = np.ones((3, 5), dtype=float)

In [57]:
np.full((3, 5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

### Создание массива заполненный линейной последовательностью начинающейся с 0 и заканчивающийся 20 с шагом 2

In [58]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Создание массива из пяти значений равномерно располагающихся между 0 и 1

In [66]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Создание массива 3 на 3 нормально распределенных случайных значений от 0 до 1

In [69]:
np.random.random((3, 3))

array([[0.5511749 , 0.01964466, 0.8201668 ],
       [0.19153347, 0.17993987, 0.12474744],
       [0.00191199, 0.23216539, 0.82930222]])

### Создание массива 3 на 3 нормально распределенных случайных значений с медианой 0 и стандартным отклонением 1

In [75]:
np.random.normal(0, 1, (3, 3))

array([[-0.52985771, -0.23724434, -0.35097401],
       [-1.48028779, -0.98293208,  0.5111052 ],
       [ 0.86831141,  0.05753606,  0.74093488]])

In [83]:
np.eye(3, dtype=int)  # единичная диагональная матрица

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])