In [13]:
import numpy as np

a = np.arange(5)
a.dtype

dtype('int64')

In [27]:
# two by two array
m = np.array([np.arange(4), np.arange(4)])
m.itemsize

8

**Краткие обозначения типов данных:**  
*integer: 'i';*    
*unsigned integer: 'u';*  
*single precision float: 'f';    
double precision float: 'd';  
boolean: 'b';  
complex: 'D';  
string: 'S';  
unicode: 'U';  
void: 'V';*    
Добавочный символ: 2, 4, 8 соответствует битам 16, 32, 64 соответственно

In [36]:
np.arange(7, dtype='i4')

array([0, 1, 2, 3, 4, 5, 6], dtype=int32)

###  Атрибуты dtype

In [61]:
# изучить подробнее позже
t = np.dtype('float64')
print(t.char)
print(t.type)
print(t.str)
t2 = np.dtype([('name', 'str_', 40), ('numitems', 'int32'), ('price', 'float32')])
t2

d
<class 'numpy.float64'>
<f8


dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

### Slicing

In [62]:
b = np.arange(24).reshape(2,3,4)

In [64]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [68]:
b[0] # можно записать также как b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
b[:, 2, 2]

array([10, 22])

In [73]:
b[1, ...]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [103]:
b[::-1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

## Разница между reval() и flatten()

In [108]:
b.ravel() # returned view

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [109]:
b.flatten() # returned copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [110]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [113]:
np.ravel(b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

Разница между view и copy аналогична shallow copy в python

In [117]:
b.resize(2,12) # аналогично reshape но изменяет сам исходный массив

In [101]:
str_arr = np.array(['Hello', 'Neel'])

In [99]:
str_arr

array(['Hello', 'World'], dtype='<U5')

## Matrices

In [126]:
A = np.mat('1, 2, 3; 4, 5, 6; 7, 8, 9') # creation from string
print('Creation matrix from string')
A

Creation matrix from string


matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [129]:
# Transpose matrix
print('Tranpose matrix: ') # Транспонирвоание матрица
A.T

Tranpose matrix: 


matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [130]:
print('Invering matrix') # обратная матрица
A.I

Invering matrix


matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])